routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Route::resource('inscriptions', 'InscriptionController');
Route::get('/inscriptions/{id_formation}/create/', 'InscriptionController@create')->name('inscriptions.create');

//Route::get('/presences/{id_formation}', 'InscriptionController@create')->name('inscriptions.create');

Route::resource('abonnements', 'AbonnementController');
Route::get('/abonnements/list-inscrits/{id_formation}', 'InscriptionController@listInscrits')->name('abonnements.list');
Route::patch('/abonnements/desactiver_class/{abonnement_id}/{calsse_id}', 'AbonnementController@desactiver_class')->name('abonnements.desactiver_class');

Route::get('/paiements/{id_formation}', 'PaiementController@index')->name('paiements.list');
Route::post('/paiements/{id_formation}', 'PaiementController@index')->name('paiements.filter');
Route::post('/paiements-add', 'PaiementController@add')->name('paiements.add');
Route::patch('/paiements-update', 'PaiementController@update')->name('paiements.update');

Route::get('/abonnements/{id}/info', 'AbonnementController@show')->name('abonnements.info');
Route::get('/abonnements/{id}/paiements', 'AbonnementController@show')->name('abonnements.paiements');
Route::get('/abonnements/{id}/presences', 'AbonnementController@show')->name('abonnements.presences');
Route::get('/abonnements/{id}/enfant', 'AbonnementController@show')->name('abonnements.enfant');

Route::resource('modules', 'ModuleController');
Route::resource('niveaux', 'NiveauController');
Route::resource('groupes', 'GroupeController');
Route::resource('salles', 'SalleController');
Route::resource('horaires', 'HoraireController');
Route::resource('formations', 'FormationController');
Route::resource('enfants', 'EnfantController');

Route::get('/classes', 'CalsseController@sessionActive')->name('classes.all');
Route::get('/classes/display/{id_session}', 'CalsseController@index')->name('classes.index');
Route::get('/classes/determine/{id_session?}', 'CalsseController@determine')->name('classes.determine');
Route::get('/classes/determine/creat/{id_formation}/{id_horaire}/{id_salle}', 'CalsseController@creat')->name('classes.creat');
Route::post('/classes/determine', 'CalsseController@store')->name('classes.store');
Route::get('/classes/determine/edit/{id_classe}', 'CalsseController@edit')->name('classes.edit');
Route::patch('/classes/determine/{classe}', 'CalsseController@update')->name('classes.update');
Route::delete('/classes/determine/{classe}', 'CalsseController@destroy')->name('classes.destroy');

app/Groupe.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Groupe extends Model
{
    protected $table = 'groupes';

    protected $fillable = ['nom', 'niveau_id'];

    public function niveau()
    {
        return $this->belongsTo('\App\Niveau');
    }

    public function classes()
    {
        return $this->hasMany('\App\Calsse');
    }
}

app/Http/Controllers/GroupeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Niveau;
use App\Groupe;

use Session;

class GroupeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $groupes = Groupe::all();

        return view('groupes.index', compact('groupes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $niveaux = Niveau::all()->sortBy("rang");

        return view('groupes.add', compact('niveaux'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, array(
            'niveau_id' => 'required|numeric|exists:niveau,id',
            'nom' => 'required|max:255|unique:groupes,nom,NULL,id,niveau_id,'.$request->niveau_id
        ));

        $groupe = new Groupe;
        $groupe->niveau_id = $request->niveau_id;
        $groupe->nom = $request->nom;
        $groupe->save();

        Session::flash('success', 'Le groupe a été créé!');

        return redirect()->route('groupes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $niveaux = Niveau::all();

        $groupe = Groupe::find($id);

        return view('groupes.edit', compact('groupe', 'niveaux'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $groupe = Groupe::find($id);

        $this->validate($request, array(
            'niveau_id' => 'required|numeric|exists:niveau,id',
            'nom' => 'required|max:255|unique:groupes,nom,'.$groupe->id.',id,niveau_id,'.$request->niveau_id
        ));

        $groupe->niveau_id = $request->niveau_id;
        $groupe->nom = $request->nom;
        $groupe->save();

        Session::flash('success', 'Le groupe a été modifié!');

        return redirect()->route('groupes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $groupe = Groupe::find($id);
        $groupe->delete();

        $response = array(
            'status' => 'success'
        );

        return response()->json($response);
    }
}

resources/views/groupes/add.blade.php
@extends('layouts.app')

@section('title', 'Ajouter un groupe')

@section('style')



@endsection

@section('content')




    <!-- .row -->
    <div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title m-b-0">Formulaire de création un nouveau groupe</h3>
                <p class="text-muted m-b-30 font-13"> Tous les champs en (*) sont obligatoires </p>

                @if ($errors->any())

                    @foreach ($errors->all() as $error)
                        <div class="alert alert-danger alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            {{ $error }} </div>
                    @endforeach

                @endif

                <form class="form" method="POST" action="{{ route('groupes.store') }}" data-toggle="validator">
                    {{ csrf_field() }}

                    <div class="form-group row">
                        <label for="niveau_id" class="col-2 col-form-label">Module (*)</label>
                        <div class="col-10">
                            <select class="form-control custom-select col-12" name="niveau_id" id="niveau_id" data-minlength="1" required>
                                <option  value="" selected>Choisir...</option>
                                @foreach($niveaux as $niveau)
                                <option value="{{ $niveau->id }}">{{ $niveau->module->titre }} --> {{ $niveau->nom }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="titre" class="col-2 col-form-label">Nom (*)</label>
                        <div class="col-10">
                            <input class="form-control" type="text" value="" id="nom" name="nom" required>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Enregisrer</button>
                    <a href="{{ route('groupes.index') }}" class="btn btn-inverse waves-effect waves-light">Annuler</a>
                </form>
            </div>
        </div>
    </div>
    <!-- /.row -->

@endsection

@section('scripts')
    <script src="{{ asset('backend/eliteadmin/js/custom.min.js') }}"></script>
    <script src="{{ asset('backend/eliteadmin/js/validator.js') }}"></script>

    <script>
        $(document).ready(function() {


        });
    </script>

@endsection

resources/views/groupes/edit.blade.php
@extends('layouts.app')

@section('title', 'Modifier le groupe ' . $groupe->nom )

@section('style')



@endsection

@section('content')




    <!-- .row -->
    <div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title m-b-0">Formulaire de modification d'un groupe</h3>
                <p class="text-muted m-b-30 font-13"> Tous les champs en (*) sont obligatoires </p>

                @if ($errors->any())

                    @foreach ($errors->all() as $error)
                        <div class="alert alert-danger alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            {{ $error }} </div>
                    @endforeach

                @endif

                <form class="form" method="POST" action="{{ route('groupes.update', $groupe->id) }}" data-toggle="validator">
                    {{ csrf_field() }}
                    {{ method_field('PATCH') }}

                    <div class="form-group row">
                        <label for="niveau_id" class="col-2 col-form-label">Module (*)</label>
                        <div class="col-10">
                            <select class="form-control custom-select col-12" name="niveau_id" id="niveau_id" data-minlength="1" required>
                                <option  value="">Choisir...</option>
                                @foreach($niveaux as $niveau)
                                    <option value="{{ $niveau->id }}"
                                    @if($niveau->id == $groupe->niveau_id)
                                    selected
                                    @endif
                                    >{{ $niveau->module->titre }} --> {{ $niveau->nom }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="titre" class="col-2 col-form-label">Nom (*)</label>
                        <div class="col-10">
                            <input class="form-control" type="text" value="{{ $groupe->nom }}" id="nom" name="nom" required>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Enregisrer</button>
                    <a href="{{ route('groupes.index') }}" class="btn btn-inverse waves-effect waves-light">Annuler</a>
                </form>
            </div>
        </div>
    </div>
    <!-- /.row -->

@endsection

@section('scripts')
    <script src="{{ asset('backend/eliteadmin/js/custom.min.js') }}"></script>
    <script src="{{ asset('backend/eliteadmin/js/validator.js') }}"></script>

    <script>
        $(document).ready(function() {


        });
    </script>

@endsection

resources/views/groupes/index.blade.php
@extends('layouts.app')

@section('title', 'En total ( ' . $groupes->count() . ' ) Groupes' )

@section('style')
    <link href="{{ asset('backend/plugins/bower_components/datatables/jquery.dataTables.min.css') }}" rel="stylesheet">

@endsection

@section('content')

    @if(Session::has('success'))
        <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            {{ Session::get('success') }} </div>
    @endif

    <!-- .row -->
    <div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <div class="table-responsive">
                    <table id="table-groupes" class="table table-bordered table-hover color-bordered-table success-bordered-table">
                        <thead>
                        <tr>
                            <th>Le Groupe</th>
                            <th>Le Niveau</th>
                            <th>Le Module</th>
                            <th class="text-nowrap">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach( $groupes as $groupe)
                        <tr id="element_{{ $groupe->id }}">
                            <td>{{ $groupe->nom }}</td>
                            <td>{{ $groupe->niveau->nom }}</td>
                            <td>{{ $groupe->niveau->module->titre }}</td>
                            <td class="text-nowrap">
                                <a href="{{ route('groupes.edit', $groupe->id) }}" data-toggle="tooltip" data-original-title="Modifier"> <i class="fa fa-pencil text-inverse m-r-10"></i> </a>
                                <a href="javascript:void(0);" data-url="{{ route('groupes.destroy', $groupe->id) }}" data-id="{{ $groupe->id }}" data-token="{{ csrf_token() }}" data-toggle="tooltip" data-original-title="Supprimer" class="sa-warning"> <i class="fa fa-close text-danger"></i> </a>
                            </td>
                        </tr>
                        @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->

    <!-- .row -->
    <div class="row">
        <div class="col-sm-12">
            <a href="{{ route('groupes.create') }}" class="btn btn-info btn-md btn-block">Ajouter un groupe</a>
        </div>

    </div>
    <!-- /.row -->



@endsection

@section('scripts')
    <script src="{{ asset('backend/eliteadmin/js/custom.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/bower_components/datatables/jquery.dataTables.min.js') }}"></script>

    <script>
        $(document).ready(function() {

            $('#table-groupes').DataTable({
                "paging":   false,
                "ordering": true,
                "info":     true,
                "language": {
                    "sProcessing":     "Traitement en cours...",
                    "sSearch":         "Rechercher&nbsp;:",
                    "sLengthMenu":     "Afficher _MENU_ &eacute;l&eacute;ments",
                    "sInfo":           "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
                    "sInfoEmpty":      "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
                    "sInfoFiltered":   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
                    "sInfoPostFix":    "",
                    "sLoadingRecords": "Chargement en cours...",
                    "sZeroRecords":    "Aucun &eacute;l&eacute;ment &agrave; afficher",
                    "sEmptyTable":     "Aucune donn&eacute;e disponible dans le tableau",
                    "oPaginate": {
                        "sFirst":      "Premier",
                        "sPrevious":   "Pr&eacute;c&eacute;dent",
                        "sNext":       "Suivant",
                        "sLast":       "Dernier"
                    },
                    "oAria": {
                        "sSortAscending":  ": activer pour trier la colonne par ordre croissant",
                        "sSortDescending": ": activer pour trier la colonne par ordre d&eacute;croissant"
                    }
                }
            });


            //Warning Message
            $('.sa-warning').click(function(){
                var id = $(this).data("id");
                var token = $(this).data("token");
                var url = $(this).data("url");

                swal({
                    title: "Êtes-vous sûr?",
                    text: "Vous ne pourrez pas récupérer ce groupe!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Oui, supprimez-le!",
                    closeOnConfirm: false
                }, function(){

                    var _dataElemen = {
                        _token : token,
                        _method: "DELETE"
                    };


                    $.ajax({
                        type: 'DELETE',
                        url: url,
                        data: _dataElemen,
                        dataType: 'json',
                        success: function(data) {

                            $('#element_'+id).remove();

                            swal("Supprimé!", "Votre niveau a été supprimé.", "success");
                        },
                        error: function(data){
                            //console.log(data);

                            swal("Supprimé!", "Votre niveau a été supprimé.", "success");
                        }
                    });
                });
            });

        });
    </script>

@endsection