routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Route::resource('inscriptions', 'InscriptionController');
Route::get('/inscriptions/{id_formation}/create/', 'InscriptionController@create')->name('inscriptions.create');

//Route::get('/presences/{id_formation}', 'InscriptionController@create')->name('inscriptions.create');

Route::resource('abonnements', 'AbonnementController');
Route::get('/abonnements/list-inscrits/{id_formation}', 'InscriptionController@listInscrits')->name('abonnements.list');
Route::patch('/abonnements/desactiver_class/{abonnement_id}/{calsse_id}', 'AbonnementController@desactiver_class')->name('abonnements.desactiver_class');

Route::get('/paiements/{id_formation}', 'PaiementController@index')->name('paiements.list');
Route::post('/paiements/{id_formation}', 'PaiementController@index')->name('paiements.filter');
Route::post('/paiements-add', 'PaiementController@add')->name('paiements.add');
Route::patch('/paiements-update', 'PaiementController@update')->name('paiements.update');

Route::get('/abonnements/{id}/info', 'AbonnementController@show')->name('abonnements.info');
Route::get('/abonnements/{id}/paiements', 'AbonnementController@show')->name('abonnements.paiements');
Route::get('/abonnements/{id}/presences', 'AbonnementController@show')->name('abonnements.presences');
Route::get('/abonnements/{id}/enfant', 'AbonnementController@show')->name('abonnements.enfant');

Route::resource('modules', 'ModuleController');
Route::resource('niveaux', 'NiveauController');
Route::resource('groupes', 'GroupeController');
Route::resource('salles', 'SalleController');
Route::resource('horaires', 'HoraireController');
Route::resource('formations', 'FormationController');
Route::resource('enfants', 'EnfantController');

Route::get('/classes', 'CalsseController@sessionActive')->name('classes.all');
Route::get('/classes/display/{id_session}', 'CalsseController@index')->name('classes.index');
Route::get('/classes/determine/{id_session?}', 'CalsseController@determine')->name('classes.determine');
Route::get('/classes/determine/creat/{id_formation}/{id_horaire}/{id_salle}', 'CalsseController@creat')->name('classes.creat');
Route::post('/classes/determine', 'CalsseController@store')->name('classes.store');
Route::get('/classes/determine/edit/{id_classe}', 'CalsseController@edit')->name('classes.edit');
Route::patch('/classes/determine/{classe}', 'CalsseController@update')->name('classes.update');
Route::delete('/classes/determine/{classe}', 'CalsseController@destroy')->name('classes.destroy');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    @include('layouts.head')


</head>

<body>
    @include('layouts.preloader')

    <div id="wrapper">
        @include('layouts.header')

        @include('layouts.leftSidebar')
        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">

                @include('layouts.title')

                @if(Session::has('flash_message'))
                    <div class="row">
                        <div class="col-md-12">
                            <div class="alert alert-success"><em> {!! session('flash_message') !!}</em>
                            </div>
                        </div>
                    </div>
                @endif


                @yield('content')

                @include('layouts.rightSidebar')
            </div>
            <!-- /.container-fluid -->
            @include('layouts.footer')
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    @include('layouts.script')
    <!-- Custom Theme JavaScript -->
    @yield('scripts')
</body>
</html>

resources/views/layouts/appError.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    @include('layouts.head')


</head>

<body>
    @include('layouts.preloader')

    <div id="wrapper" class="error-page">

        @yield('content')


    </div>
    <!-- /#wrapper -->
    @include('layouts.script')
    <!-- Custom Theme JavaScript -->
    @yield('scripts')
</body>
</html>

resources/views/layouts/appLogin.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    @include('layouts.head')

    @yield('style')
</head>

<body>
    @include('layouts.preloader')

    <div id="wrapper" class="login-register">
        <!-- Page Content -->
        <div class="login-box">
            @yield('content')

        </div>
        <!-- /#login-box -->
    </div>
    <!-- /#wrapper -->
    @include('layouts.script')
    <!-- Custom Theme JavaScript -->
    @yield('scripts')
</body>
</html>

resources/views/layouts/breadcrumbs.blade.php
@switch(request()->route()->getName())
@case('modules.edit')
{!! Breadcrumbs::render('modules.edit', $module) !!}
@break

@case('niveaux.edit')
{!! Breadcrumbs::render('niveaux.edit', $module) !!}
@break

@case('groupes.edit')
{!! Breadcrumbs::render('groupes.edit', $groupe) !!}
@break

@case('salles.edit')
{!! Breadcrumbs::render('salles.edit', $salle) !!}
@break

@case('horaires.edit')
{!! Breadcrumbs::render('horaires.edit', $horaire) !!}
@break

@case('formations.edit')
{!! Breadcrumbs::render('formations.edit', $formation) !!}
@break

@case('enfants.edit')
{!! Breadcrumbs::render('enfants.edit', $enfant) !!}
@break

@case('classes.index')
{!! Breadcrumbs::render('classes.index', $formation) !!}
@break

@case('classes.determine')
{!! Breadcrumbs::render('classes.determine', $formation) !!}
@break

@case('classes.creat')
{!! Breadcrumbs::render('classes.creat', $formation) !!}
@break

@case('classes.edit')
{!! Breadcrumbs::render('classes.edit', $classe) !!}
@break

@case('inscriptions.create')
{!! Breadcrumbs::render('inscriptions.create', $formation) !!}
@break

@case('abonnements.list')
{!! Breadcrumbs::render('abonnements.list', $formation) !!}
@break

@case('abonnements.show')
{!! Breadcrumbs::render('abonnements.show', $abonnement) !!}
@break

@case('abonnements.info')
{!! Breadcrumbs::render('abonnements.show', $abonnement) !!}
@break

@case('abonnements.paiements')
{!! Breadcrumbs::render('abonnements.paiements', $abonnement) !!}
@break
@case('abonnements.enfant')
{!! Breadcrumbs::render('abonnements.show', $abonnement) !!}
@break
@case('abonnements.presences')
{!! Breadcrumbs::render('abonnements.show', $abonnement) !!}
@break

@case('paiements.list')
{!! Breadcrumbs::render('paiements.list', $formation) !!}
@break

@case('paiements.filter')
{!! Breadcrumbs::render('paiements.list', $formation) !!}
@break

@default
{!! Breadcrumbs::render() !!}
@endswitch

resources/views/layouts/footer.blade.php
<footer class="footer text-center"> 2017 &copy; Robokids. created by digipanda.net </footer>

resources/views/layouts/head.blade.php
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('backend/plugins/images/favicon.png') }}">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Panda CMS') }} - @yield('title')</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{ asset('backend/eliteadmin/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('backend/plugins/bower_components/bootstrap-extension/css/bootstrap-extension.css') }}" rel="stylesheet">
    <!-- Menu CSS -->
    <link href="{{ asset('backend/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.css') }}" rel="stylesheet">
    <!-- morris CSS -->
    <link href="{{ asset('backend/plugins/bower_components/morrisjs/morris.css') }}" rel="stylesheet">
    <!-- animation CSS -->
    <link href="{{ asset('backend/eliteadmin/css/animate.css') }}" rel="stylesheet">

    <!--alerts CSS -->
    <link href="{{ asset('backend/plugins/bower_components/sweetalert/sweetalert.css') }}" rel="stylesheet">

    @yield('style')

    <!-- Custom CSS -->
    <link href="{{ asset('backend/eliteadmin/css/style.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">

    <!-- color CSS -->
    <link href="{{ asset('backend/eliteadmin/css/colors/blue.css') }}" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

resources/views/layouts/header.blade.php
    <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top m-b-0">
            <div class="navbar-header"> <a class="navbar-toggle hidden-sm hidden-md hidden-lg " href="javascript:void(0)" data-toggle="collapse" data-target=".navbar-collapse"><i class="ti-menu"></i></a>
                <div class="top-left-part"><a class="logo" href="{{ route('home') }}"><b><img src="{{ asset('backend/plugins/images/eliteadmin-logo.png') }}" alt="home" /></b><span class="hidden-xs"><img src="{{ asset('backend/plugins/images/eliteadmin-text.png') }}" alt="home" /></span></a></div>
                <ul class="nav navbar-top-links navbar-left hidden-xs">
                    <li><a href="javascript:void(0)" class="open-close hidden-xs waves-effect waves-light"><i class="icon-arrow-left-circle ti-menu"></i></a></li>

                </ul>
                <ul class="nav navbar-top-links navbar-right pull-right">

                    <li class="right-side-toggle">

                    </li>

                    <!-- /.dropdown -->
                </ul>
            </div>
            <!-- /.navbar-header -->
            <!-- /.navbar-top-links -->
            <!-- /.navbar-static-side -->
        </nav>

resources/views/layouts/leftSidebar.blade.php
    <!-- Left navbar-header -->
        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse slimscrollsidebar">

                <ul class="nav" id="side-menu">

                    <li><a href="{{ route('home') }}" class="waves-effect"><i data-icon="v" class="linea-icon linea-basic fa-fw"></i> <span class="hide-menu">Tableaux de bord</span></a> </li>

                    @widget('FormationMenus')
                    <li><a href="{{ route('enfants.index') }}" class="waves-effect"><i class="fa fa-users fa-fw"></i> <span class="hide-menu">Les enfants</span></a> </li>
                    <li><a href="{{ route('formations.index') }}" class="waves-effect"><i class="fa fa-graduation-cap fa-fw"></i> <span class="hide-menu">Les sessions</span></a> </li>
                    <li><a href="{{ route('horaires.index') }}" class="waves-effect"><i data-icon="b" class="linea-icon linea-basic fa-fw"></i> <span class="hide-menu">Les horaires</span></a> </li>
                    <li><a href="{{ route('salles.index') }}" class="waves-effect"><i class="fa fa-building-o fa-fw"></i> <span class="hide-menu">Les salles</span></a> </li>
                    <li><a href="{{ route('groupes.index') }}" class="waves-effect"><i class="fa fa-bank fa-fw"></i> <span class="hide-menu">Les groupes</span></a> </li>
                    <li><a href="{{ route('niveaux.index') }}" class="waves-effect"><i data-icon="v" class="linea-icon linea-software fa-fw"></i> <span class="hide-menu">Les niveaux</span></a> </li>
                    <li><a href="{{ route('modules.index') }}" class="waves-effect"><i data-icon="7" class="linea-icon linea-basic fa-fw"></i> <span class="hide-menu">Les modules</span></a> </li>








                    <li><a href="{{ route('logout') }}" class="waves-effect" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();"><i class="icon-logout fa-fw"></i> <span class="hide-menu">Déconnexion</span></a></li>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>

                </ul>
            </div>
        </div>
        <!-- Left navbar-header end -->

resources/views/layouts/preloader.blade.php
<!-- Preloader -->
    <div class="preloader">
        <div class="cssload-speeding-wheel"></div>
    </div>

resources/views/layouts/rightSidebar.blade.php
{{--
<!-- .right-sidebar -->
<div class="right-sidebar">
    <div class="slimscrollright">
        <div class="rpanel-title"> Service Panel <span><i class="ti-close right-side-toggle"></i></span> </div>
        <div class="r-panel-body">
            <ul class="m-t-20 chatonline">
                <li><b>Chat option</b></li>
                <li>
                    <a href="javascript:void(0)"><img src="{{ asset('backend/plugins/images/users/varun.jpg') }}" alt="user-img" class="img-circle"> <span>Varun Dhavan <small class="text-success">online</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="{{ asset('backend/plugins/images/users/genu.jpg') }}" alt="user-img" class="img-circle"> <span>Genelia Deshmukh <small class="text-warning">Away</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="{{ asset('backend/plugins/images/users/ritesh.jpg') }}" alt="user-img" class="img-circle"> <span>Ritesh Deshmukh <small class="text-danger">Busy</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="{{ asset('backend/plugins/images/users/arijit.jpg') }}" alt="user-img" class="img-circle"> <span>Arijit Sinh <small class="text-muted">Offline</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="{{ asset('backend/plugins/images/users/govinda.jpg') }}" alt="user-img" class="img-circle"> <span>Govinda Star <small class="text-success">online</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="{{ asset('backend/plugins/images/users/hritik.jpg') }}" alt="user-img" class="img-circle"> <span>John Abraham<small class="text-success">online</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="{{ asset('backend/plugins/images/users/john.jpg') }}" alt="user-img" class="img-circle"> <span>Hritik Roshan<small class="text-success">online</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="{{ asset('backend/plugins/images/users/pawandeep.jpg') }}" alt="user-img" class="img-circle"> <span>Pwandeep rajan <small class="text-success">online</small></span></a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- /.right-sidebar -->
--}}

resources/views/layouts/script.blade.php
<!-- jQuery -->
    <script src="{{ asset('backend/plugins/bower_components/jquery/dist/jquery.min.js') }}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{{ asset('backend/eliteadmin/bootstrap/dist/js/tether.min.js') }}"></script>
    <script src="{{ asset('backend/eliteadmin/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/bower_components/bootstrap-extension/js/bootstrap-extension.min.js') }}"></script>
    <!-- Menu Plugin JavaScript -->
    <script src="{{ asset('backend/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js') }}"></script>
    <!--Counter js -->
    <script src="{{ asset('backend/plugins/bower_components/waypoints/lib/jquery.waypoints.js') }}"></script>
    <script src="{{ asset('backend/plugins/bower_components/counterup/jquery.counterup.min.js') }}"></script>
    <!--slimscroll JavaScript -->
    <script src="{{ asset('backend/eliteadmin/js/jquery.slimscroll.js') }}"></script>
    <!--Wave Effects -->
    <script src="{{ asset('backend/eliteadmin/js/waves.js') }}"></script>
    <!--Morris JavaScript -->
    <script src="{{ asset('backend/plugins/bower_components/raphael/raphael-min.js') }}"></script>
    <script src="{{ asset('backend/plugins/bower_components/morrisjs/morris.js') }}"></script>
    <script src="{{ asset('backend/plugins/bower_components/jquery-sparkline/jquery.sparkline.min.js') }}"></script>

    <!-- Sweet-Alert  -->
    <script src="{{ asset('backend/plugins/bower_components/sweetalert/sweetalert.min.js') }}"></script>

resources/views/layouts/title.blade.php
<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">@yield('title')</h4>
    </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
        @include('layouts.breadcrumbs')
    </div>
    <!-- /.col-lg-12 -->
</div>