routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Route::resource('inscriptions', 'InscriptionController');
Route::get('/inscriptions/{id_formation}/create/', 'InscriptionController@create')->name('inscriptions.create');

//Route::get('/presences/{id_formation}', 'InscriptionController@create')->name('inscriptions.create');

Route::resource('abonnements', 'AbonnementController');
Route::get('/abonnements/list-inscrits/{id_formation}', 'InscriptionController@listInscrits')->name('abonnements.list');
Route::patch('/abonnements/desactiver_class/{abonnement_id}/{calsse_id}', 'AbonnementController@desactiver_class')->name('abonnements.desactiver_class');

Route::get('/paiements/{id_formation}', 'PaiementController@index')->name('paiements.list');
Route::post('/paiements/{id_formation}', 'PaiementController@index')->name('paiements.filter');
Route::post('/paiements-add', 'PaiementController@add')->name('paiements.add');
Route::patch('/paiements-update', 'PaiementController@update')->name('paiements.update');

Route::get('/abonnements/{id}/info', 'AbonnementController@show')->name('abonnements.info');
Route::get('/abonnements/{id}/paiements', 'AbonnementController@show')->name('abonnements.paiements');
Route::get('/abonnements/{id}/presences', 'AbonnementController@show')->name('abonnements.presences');
Route::get('/abonnements/{id}/enfant', 'AbonnementController@show')->name('abonnements.enfant');

Route::resource('modules', 'ModuleController');
Route::resource('niveaux', 'NiveauController');
Route::resource('groupes', 'GroupeController');
Route::resource('salles', 'SalleController');
Route::resource('horaires', 'HoraireController');
Route::resource('formations', 'FormationController');
Route::resource('enfants', 'EnfantController');

Route::get('/classes', 'CalsseController@sessionActive')->name('classes.all');
Route::get('/classes/display/{id_session}', 'CalsseController@index')->name('classes.index');
Route::get('/classes/determine/{id_session?}', 'CalsseController@determine')->name('classes.determine');
Route::get('/classes/determine/creat/{id_formation}/{id_horaire}/{id_salle}', 'CalsseController@creat')->name('classes.creat');
Route::post('/classes/determine', 'CalsseController@store')->name('classes.store');
Route::get('/classes/determine/edit/{id_classe}', 'CalsseController@edit')->name('classes.edit');
Route::patch('/classes/determine/{classe}', 'CalsseController@update')->name('classes.update');
Route::delete('/classes/determine/{classe}', 'CalsseController@destroy')->name('classes.destroy');

resources/views/niveaux/add.blade.php
@extends('layouts.app')

@section('title', 'Ajouter un niveau')

@section('style')



@endsection

@section('content')




    <!-- .row -->
    <div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title m-b-0">Formulaire de création un nouveau niveau</h3>
                <p class="text-muted m-b-30 font-13"> Tous les champs en (*) sont obligatoires </p>

                @if ($errors->any())

                    @foreach ($errors->all() as $error)
                        <div class="alert alert-danger alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            {{ $error }} </div>
                    @endforeach

                @endif

                <form class="form" method="POST" action="{{ route('niveaux.store') }}" data-toggle="validator">
                    {{ csrf_field() }}

                    <div class="form-group row">
                        <label for="module_id" class="col-2 col-form-label">Module (*)</label>
                        <div class="col-10">
                            <select class="form-control custom-select col-12" name="module_id" id="module_id" data-minlength="1" required>
                                <option  value="" selected>Choisir...</option>
                                @foreach($modules as $module)
                                <option value="{{ $module->id }}">{{ $module->titre }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="titre" class="col-2 col-form-label">Nom (*)</label>
                        <div class="col-10">
                            <input class="form-control" type="text" value="" id="nom" name="nom" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="code" class="col-2 col-form-label">Rang (*)</label>
                        <div class="col-10">
                            <input class="form-control" type="number" value="0" id="rang" name="rang" min="1" required>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Enregisrer</button>
                    <a href="{{ route('niveaux.index') }}" class="btn btn-inverse waves-effect waves-light">Annuler</a>
                </form>
            </div>
        </div>
    </div>
    <!-- /.row -->

@endsection

@section('scripts')
    <script src="{{ asset('backend/eliteadmin/js/custom.min.js') }}"></script>
    <script src="{{ asset('backend/eliteadmin/js/validator.js') }}"></script>

    <script>
        $(document).ready(function() {


        });
    </script>

@endsection

resources/views/niveaux/edit.blade.php
@extends('layouts.app')

@section('title', 'Modifier le niveau ' . $niveau->nom )

@section('style')



@endsection

@section('content')




    <!-- .row -->
    <div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title m-b-0">Formulaire de modification d'un niveau</h3>
                <p class="text-muted m-b-30 font-13"> Tous les champs en (*) sont obligatoires </p>

                @if ($errors->any())

                    @foreach ($errors->all() as $error)
                        <div class="alert alert-danger alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            {{ $error }} </div>
                    @endforeach

                @endif

                <form class="form" method="POST" action="{{ route('niveaux.update', $niveau->id) }}" data-toggle="validator">
                    {{ csrf_field() }}
                    {{ method_field('PATCH') }}

                    <div class="form-group row">
                        <label for="module_id" class="col-2 col-form-label">Module (*)</label>
                        <div class="col-10">
                            <select class="form-control custom-select col-12" name="module_id" id="module_id" data-minlength="1" required>
                                <option  value="">Choisir...</option>
                                @foreach($modules as $module)
                                    <option value="{{ $module->id }}"
                                    @if($module->id == $niveau->module_id)
                                    selected
                                    @endif
                                    >{{ $module->titre }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="titre" class="col-2 col-form-label">Nom (*)</label>
                        <div class="col-10">
                            <input class="form-control" type="text" value="{{ $niveau->nom }}" id="nom" name="nom" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="code" class="col-2 col-form-label">Code (*)</label>
                        <div class="col-10">
                            <input class="form-control" type="number" value="{{ $niveau->rang }}" id="rang" name="rang" min="1" required>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Enregisrer</button>
                    <a href="{{ route('niveaux.index') }}" class="btn btn-inverse waves-effect waves-light">Annuler</a>
                </form>
            </div>
        </div>
    </div>
    <!-- /.row -->

@endsection

@section('scripts')
    <script src="{{ asset('backend/eliteadmin/js/custom.min.js') }}"></script>
    <script src="{{ asset('backend/eliteadmin/js/validator.js') }}"></script>

    <script>
        $(document).ready(function() {


        });
    </script>

@endsection

resources/views/niveaux/index.blade.php
@extends('layouts.app')

@section('title', 'Les niveaux')

@section('style')



@endsection

@section('content')

    @if(Session::has('success'))
        <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            {{ Session::get('success') }} </div>
    @endif

    <!-- .row -->
    <div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover color-bordered-table purple-bordered-table">
                        <thead>
                        <tr>
                            <th>Le Module</th>
                            <th>Le Niveau</th>
                            <th>Rang</th>

                            <th class="text-nowrap">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach( $niveaux as $niveau)
                        <tr id="element_{{ $niveau->id }}">
                            <td>{{ $niveau->module->titre }}</td>
                            <td>{{ $niveau->nom }}</td>
                            <td><span class="label label-info">{{ $niveau->rang }}</span></td>
                            <td class="text-nowrap">
                                <a href="{{ route('niveaux.edit', $niveau->id) }}" data-toggle="tooltip" data-original-title="Modifier"> <i class="fa fa-pencil text-inverse m-r-10"></i> </a>
                                <a href="javascript:void(0);" data-url="{{ route('niveaux.destroy', $niveau->id) }}" data-id="{{ $niveau->id }}" data-token="{{ csrf_token() }}" data-toggle="tooltip" data-original-title="Supprimer" class="sa-warning"> <i class="fa fa-close text-danger"></i> </a>
                            </td>
                        </tr>
                        @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->

    <!-- .row -->
    <div class="row">
        <div class="col-sm-12">
            <a href="{{ route('niveaux.create') }}" class="btn btn-info btn-md btn-block">Ajouter un niveau</a>
        </div>

    </div>
    <!-- /.row -->



@endsection

@section('scripts')
    <script src="{{ asset('backend/eliteadmin/js/custom.min.js') }}"></script>

    <script>
        $(document).ready(function() {

            //Warning Message
            $('.sa-warning').click(function(){
                var id = $(this).data("id");
                var token = $(this).data("token");
                var url = $(this).data("url");

                swal({
                    title: "Êtes-vous sûr?",
                    text: "Vous ne pourrez pas récupérer ce niveau!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Oui, supprimez-le!",
                    closeOnConfirm: false
                }, function(){

                    var _dataElemen = {
                        _token : token,
                        _method: "DELETE"
                    };


                    $.ajax({
                        type: 'DELETE',
                        url: url,
                        data: _dataElemen,
                        dataType: 'json',
                        success: function(data) {


                            if(data.status == 'success') {
                                $('#element_'+id).remove();

                                swal("Supprimé!", "Votre niveau a été supprimé.", "success");
                            } else {
                                swal("Oops...", data.message, "error");
                            }

                        },
                        error: function(data){
                            //console.log(data);
                        }
                    });
                });
            });

        });
    </script>

@endsection